// <auto-generated />
using System;
using JumpArena.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JumpArena.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("JumpArena.Models.AuditLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("InvoiceID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("LogID");

                    b.ToTable("LichSuHoatDong");
                });

            modelBuilder.Entity("JumpArena.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("LoaiSanPham");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Vé vui chơi"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Vớ"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Đồ uống"
                        });
                });

            modelBuilder.Entity("JumpArena.Models.CheckinCode", b =>
                {
                    b.Property<int>("CheckinID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CheckinTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CheckoutTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InvoiceDetailID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CheckinID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("InvoiceDetailID")
                        .IsUnique();

                    b.ToTable("MaCheckin");
                });

            modelBuilder.Entity("JumpArena.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LegalRepresentative")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerID");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("JumpArena.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalOriginalAmount")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int?>("UserID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VoucherID")
                        .HasColumnType("INTEGER");

                    b.HasKey("InvoiceID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("UserID");

                    b.HasIndex("VoucherID");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("JumpArena.Models.InvoiceDetail", b =>
                {
                    b.Property<int>("InvoiceDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvoiceID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("InvoiceDetailID");

                    b.HasIndex("InvoiceID");

                    b.HasIndex("ProductID");

                    b.ToTable("ChiTietHoaDon");
                });

            modelBuilder.Entity("JumpArena.Models.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDigital")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PaymentMethodID");

                    b.ToTable("PhuongThucThanhToan");

                    b.HasData(
                        new
                        {
                            PaymentMethodID = 1,
                            IsDigital = false,
                            MethodName = "Tiền mặt"
                        },
                        new
                        {
                            PaymentMethodID = 2,
                            IsDigital = true,
                            MethodName = "Chuyển khoản ngân hàng"
                        },
                        new
                        {
                            PaymentMethodID = 3,
                            IsDigital = true,
                            MethodName = "Thẻ tín dụng (Credit Card)"
                        },
                        new
                        {
                            PaymentMethodID = 4,
                            IsDigital = true,
                            MethodName = "Ví MoMo"
                        },
                        new
                        {
                            PaymentMethodID = 5,
                            IsDigital = true,
                            MethodName = "Ví ZaloPay"
                        });
                });

            modelBuilder.Entity("JumpArena.Models.PaymentTransaction", b =>
                {
                    b.Property<int>("PaymentTransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int>("InvoiceID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentMethodID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PaymentTransactionID");

                    b.HasIndex("InvoiceID");

                    b.HasIndex("PaymentMethodID");

                    b.ToTable("ThanhToan");
                });

            modelBuilder.Entity("JumpArena.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("SanPham");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 1,
                            Price = 140000m,
                            ProductName = "Vé người lớn (Trong tuần)",
                            StockQuantity = -1
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 1,
                            Price = 98000m,
                            ProductName = "Vé trẻ em (Trong tuần)",
                            StockQuantity = -1
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 1,
                            Price = 1000m,
                            ProductName = "Combo Sinh viên (Vé + Vớ)",
                            StockQuantity = -1
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryID = 1,
                            Price = 180000m,
                            ProductName = "Vé người lớn (Cuối tuần)",
                            StockQuantity = -1
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 1,
                            Price = 126000m,
                            ProductName = "Vé trẻ em (Cuối tuần)",
                            StockQuantity = -1
                        },
                        new
                        {
                            ProductID = 6,
                            CategoryID = 1,
                            Price = 250000m,
                            ProductName = "Vé Sự Kiện Halloween",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductID = 7,
                            CategoryID = 2,
                            Price = 29000m,
                            ProductName = "Vớ bám bạt thường",
                            StockQuantity = 500
                        },
                        new
                        {
                            ProductID = 8,
                            CategoryID = 2,
                            Price = 29000m,
                            ProductName = "Vớ Giáng Sinh",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductID = 9,
                            CategoryID = 2,
                            Price = 29000m,
                            ProductName = "Vớ Summer",
                            StockQuantity = 150
                        },
                        new
                        {
                            ProductID = 10,
                            CategoryID = 2,
                            Price = 29000m,
                            ProductName = "Vớ Sinh nhật",
                            StockQuantity = 150
                        },
                        new
                        {
                            ProductID = 11,
                            CategoryID = 3,
                            Price = 45000m,
                            ProductName = "Trà Đào Cam Sả",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductID = 12,
                            CategoryID = 3,
                            Price = 42000m,
                            ProductName = "Trà Vải",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductID = 13,
                            CategoryID = 3,
                            Price = 30000m,
                            ProductName = "Trà Chanh",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductID = 14,
                            CategoryID = 3,
                            Price = 20000m,
                            ProductName = "Pocari Sweat",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductID = 15,
                            CategoryID = 3,
                            Price = 15000m,
                            ProductName = "Sting Dâu",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductID = 16,
                            CategoryID = 3,
                            Price = 20000m,
                            ProductName = "Red Bull",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductID = 17,
                            CategoryID = 3,
                            Price = 15000m,
                            ProductName = "Coca-Cola",
                            StockQuantity = 300
                        },
                        new
                        {
                            ProductID = 18,
                            CategoryID = 3,
                            Price = 15000m,
                            ProductName = "7 Up",
                            StockQuantity = 300
                        },
                        new
                        {
                            ProductID = 19,
                            CategoryID = 3,
                            Price = 15000m,
                            ProductName = "Pepsi",
                            StockQuantity = 300
                        },
                        new
                        {
                            ProductID = 20,
                            CategoryID = 3,
                            Price = 18000m,
                            ProductName = "Olong Tea Plus",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductID = 21,
                            CategoryID = 3,
                            Price = 18000m,
                            ProductName = "Trà xanh không độ",
                            StockQuantity = 200
                        },
                        new
                        {
                            ProductID = 22,
                            CategoryID = 3,
                            Price = 10000m,
                            ProductName = "Nước suối Aquafina 500ml",
                            StockQuantity = 500
                        });
                });

            modelBuilder.Entity("JumpArena.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("RoleID");

                    b.ToTable("VaiTro");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            RoleName = "Nhân viên"
                        },
                        new
                        {
                            RoleID = 2,
                            RoleName = "Quản lý"
                        },
                        new
                        {
                            RoleID = 3,
                            RoleName = "Kế toán trưởng"
                        });
                });

            modelBuilder.Entity("JumpArena.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoleID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.ToTable("NguoiDung");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Address = "Quận 1, TPHCM",
                            BirthDate = new DateTime(1990, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nguyễn Văn Hiệp",
                            Password = "Hiep@2025",
                            RoleID = 2,
                            Username = "HiepJAQL00078"
                        },
                        new
                        {
                            UserID = 2,
                            Address = "Thành phố Thủ Đức",
                            BirthDate = new DateTime(1992, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Trần Thị Bích Loan",
                            Password = "Loan@2025",
                            RoleID = 2,
                            Username = "LoanJAQL00079"
                        },
                        new
                        {
                            UserID = 3,
                            Address = "Quận 3, TPHCM",
                            BirthDate = new DateTime(1988, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Lê Thị Mai",
                            Password = "Mai@2025",
                            RoleID = 3,
                            Username = "MaiJAKT00001"
                        },
                        new
                        {
                            UserID = 4,
                            Address = "Gò Vấp, TPHCM",
                            BirthDate = new DateTime(2003, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Trần Minh Hoàng",
                            Password = "Hoang@2025",
                            RoleID = 1,
                            Username = "HoangJAGV0001"
                        },
                        new
                        {
                            UserID = 5,
                            Address = "Bình Thạnh, TPHCM",
                            BirthDate = new DateTime(2004, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Phạm Thị Yến",
                            Password = "Yen@2025",
                            RoleID = 1,
                            Username = "YenJAGV0002"
                        },
                        new
                        {
                            UserID = 6,
                            Address = "Quận 12, TPHCM",
                            BirthDate = new DateTime(2002, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bích Đú",
                            Password = "Bich@2025",
                            RoleID = 1,
                            Username = "BichJAGV0003"
                        },
                        new
                        {
                            UserID = 7,
                            Address = "Tân Bình, TPHCM",
                            BirthDate = new DateTime(2005, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Đỗ Huyền Anh",
                            Password = "Anh@2025",
                            RoleID = 1,
                            Username = "AnhJAGV0004"
                        },
                        new
                        {
                            UserID = 8,
                            Address = "Phú Nhuận, TPHCM",
                            BirthDate = new DateTime(2003, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Võ Thành Trung",
                            Password = "Trung@2025",
                            RoleID = 1,
                            Username = "TrungJAGV0005"
                        });
                });

            modelBuilder.Entity("JumpArena.Models.Voucher", b =>
                {
                    b.Property<int>("VoucherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscountType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinimumOrderValue")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoucherCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("VoucherID");

                    b.ToTable("Voucher");

                    b.HasData(
                        new
                        {
                            VoucherID = 1,
                            Description = "Giảm 50.000 VNĐ cho đơn hàng từ 250.000 VNĐ",
                            DiscountType = "Fixed",
                            DiscountValue = 50000m,
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumOrderValue = 250000m,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VoucherCode = "GIAM50K"
                        },
                        new
                        {
                            VoucherID = 2,
                            Description = "Giảm 10% cho sinh viên",
                            DiscountType = "Percentage",
                            DiscountValue = 10m,
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumOrderValue = 0m,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VoucherCode = "SINHVIEN10"
                        },
                        new
                        {
                            VoucherID = 3,
                            Description = "Mừng Quốc Khánh 2/9, giảm 20% tổng hóa đơn",
                            DiscountType = "Percentage",
                            DiscountValue = 20m,
                            EndDate = new DateTime(2025, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumOrderValue = 0m,
                            StartDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VoucherCode = "QUOCKHANH"
                        },
                        new
                        {
                            VoucherID = 4,
                            Description = "Lễ Halloween giảm 30.000đ cho đơn >200k",
                            DiscountType = "Fixed",
                            DiscountValue = 30000m,
                            EndDate = new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumOrderValue = 200000m,
                            StartDate = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VoucherCode = "HALLOWEEN"
                        });
                });

            modelBuilder.Entity("JumpArena.Models.CheckinCode", b =>
                {
                    b.HasOne("JumpArena.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID");

                    b.HasOne("JumpArena.Models.InvoiceDetail", "InvoiceDetail")
                        .WithOne("CheckinCode")
                        .HasForeignKey("JumpArena.Models.CheckinCode", "InvoiceDetailID");

                    b.Navigation("Customer");

                    b.Navigation("InvoiceDetail");
                });

            modelBuilder.Entity("JumpArena.Models.Invoice", b =>
                {
                    b.HasOne("JumpArena.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID");

                    b.HasOne("JumpArena.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.HasOne("JumpArena.Models.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("VoucherID");

                    b.Navigation("Customer");

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("JumpArena.Models.InvoiceDetail", b =>
                {
                    b.HasOne("JumpArena.Models.Invoice", "Invoice")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JumpArena.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JumpArena.Models.PaymentTransaction", b =>
                {
                    b.HasOne("JumpArena.Models.Invoice", "Invoice")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JumpArena.Models.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("JumpArena.Models.Product", b =>
                {
                    b.HasOne("JumpArena.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("JumpArena.Models.User", b =>
                {
                    b.HasOne("JumpArena.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("JumpArena.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("JumpArena.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceDetails");

                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("JumpArena.Models.InvoiceDetail", b =>
                {
                    b.Navigation("CheckinCode")
                        .IsRequired();
                });

            modelBuilder.Entity("JumpArena.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
